In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader.data as web
from statsmodels.stats.correlation_tools import cov_nearest
from numpy.linalg import inv

In [81]:
# Black_Litterman 프레임워크 산출
# 0. 대상 종목 정보 가져오기 
# 1. 시가총액, 평균 수익률로 Prior_wgt 산출하기 
# 2. Cov_mtrx, Lambda 로 Prior_rtn 산출하기
# 3. 단위행렬(P), 전략계수(str_Q) 셋팅하기 
# 4. P와 tau로 Omega mtrx산출, str_Q로 Q array 산출하기
# 5. P와 Q와 Omega로 Post_rtn 산출, Lambda와 Post_rtn으로 Post_wgt 산출하기 

In [82]:
ret = np.array([0.0867, 0.0372, 0.39])
wgt = np.array([[0.4],
                [0.5],
                [0.1]])
cov = np.array([[0.0084,-0.0009,0.0077],
                [-0.0009,0.0016,0.0045],
                [0.0077,0.0045,0.0622]])
rf = 0.0165

In [85]:
exp_excess_rtn = np.dot(ret - rf,wgt)
exp_excess_rtn

array([0.07578])

In [86]:
var = np.dot(wgt.T,np.dot(cov,wgt))
var

array([[0.003072]])

In [87]:
lmbda = exp_excess_rtn / var
lmbda

array([[24.66796875]])

In [88]:
lmbda = 24.3820

In [89]:
pi = (lmbda * np.dot(cov, wgt) + rf)
pi

array([[0.10622576],
       [0.03819998],
       [0.2981121 ]])

In [90]:
pi = np.array([[0.1072],[0.0392],[0.2972]])
pi

array([[0.1072],
       [0.0392],
       [0.2972]])

In [91]:
P = np.array([[1,0,0],[0,1,0],[0,0,1]])
P

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [92]:
tau = 0.03

In [93]:
omega = np.dot(np.dot(P,cov),P.T) * tau * np.eye(3)
omega

array([[ 2.520e-04, -0.000e+00,  0.000e+00],
       [-0.000e+00,  4.800e-05,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  1.866e-03]])

In [94]:
cov

array([[ 0.0084, -0.0009,  0.0077],
       [-0.0009,  0.0016,  0.0045],
       [ 0.0077,  0.0045,  0.0622]])

In [95]:
bl_Q = np.array([[-0.0108],
                 [-0.0004],
                 [0.0334]])

In [96]:
Q = pi + 100 * rf * bl_Q
Q 

array([[0.08938],
       [0.03854],
       [0.35231]])

In [97]:
post_ret = pi + np.dot( np.dot( tau * np.dot(cov,P.T) , inv(omega + tau * np.dot(P,np.dot(cov,P.T)))) , (Q - np.dot(P, pi)))
post_ret

array([[0.10116556],
       [0.04080895],
       [0.31616257]])

In [98]:
post_wgt = np.dot( inv(lmbda*cov) , (post_ret - rf))
post_wgt

array([[0.35881568],
       [0.49484902],
       [0.11737328]])

In [99]:
adj_post_wgt = post_wgt/post_wgt.sum()
adj_post_wgt

array([[0.36951766],
       [0.50960831],
       [0.12087404]])